"""Add date_uploaded to AnalysisHistory

Revision ID: f2d87373d87f
Revises: 
Create Date: 2025-05-28 00:11:25.373126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d87373d87f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_uploaded', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('result',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date_uploaded')

    # ### end Alembic commands ###
